spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: ${SCHEMA_NAME}
    liquibase-schema: ${SCHEMA_NAME}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      schema: ${SCHEMA_NAME}
      maximumPoolSize: 30
      minimumIdle: 2
  jpa:
    hibernate:
      ddl-auto: ${SCHEMA_UPDATE}
    properties:
      hibernate:
        default_schema: ${SCHEMA_NAME}
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    root: ${LOG_LEVEL}